---
version: "2.1"
services:
  headphones:
    image: lscr.io/linuxserver/headphones:latest
    container_name: headphones
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/headphones/config:/config
      - ${Data_Path}/downloads:/downloads  # optional
      - ${Data_Path}/music:/music
    # ports:
    #   - 8181:8181
    network_mode: 'container:Gluetun_VPN_PIA'
    restart: unless-stopped
