version: "3"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${Master_Path}/lidarr/config:/config
      - ${Data_Path}:/data      # optional
      - ${Data_Path}/downloads:/downloads  # optional
    # network_mode: "container:Gluetun_VPN_PIA"
    ports:
      - 8686:8686
    restart: always